### ISSUE TITLE
As a user, I want to provision AWS resource and time ETL 1B edges into neo4j

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-storage-eval#15]
Convert the docker image configured https://github.com/data61/stellar-storage-eval/tree/master/neo4j-fromcsv into ansible play. 
Suggest uploading the stack-overflow data to AWS on an SSD storage. 

## AC
- Neo4j Ansible provisioning scripts updated for bulk load
- Time result for Extract & Transform of EPGM files in CSV 
- Time result to bulk load into neo4j

**Comment by bowernj** [comment]
* Neo4j bulk insert is not currently handling objects as properties (on nodes or edges)

**Comment by bowernj** [comment]
Updated AC
- Load 1B edges into AWS instance using Neo4j APOC LOAD JSON.
