### ISSUE TITLE
Bulk load into Postgres provisioned into AWS

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-storage-eval#35]
build the adjacency list as previously done. Parallel load of Folder 1..7 with 7 core vCPU. 

## AC

- Load 1B edges & 602M nodes
- Repeatable with a Readme
- Record the timings of the load as below (ET & L separately)
    * Step 2 
    * Folder 1 
    * Folder 1..7 
- Targeted to AWS

**Comment by chinkitp** [comment]
doing with tsv and finishing the load

**Comment by tmoschou** [comment]
24 executors: 1core/3GB each
Build adjacency for folder1 8 mins, or 56mins for 1-7 (back to json)

Timings here
[Book1.xlsx](https://github.com/data61/stellar-storage-eval/files/2131483/Book1.xlsx)
